// THIS FILE IS AUTO-GENERATED BY scripts/seal.mjs
// DO NOT EDIT MANUALLY — any change will invalidate the seal.
// Generated: 2026-06-03T14:56:31.292Z

export const DIRECTIVE_SEAL = "54c304c29a1093f7bb8a1a2ffc01526d96778e8372cc582580497128c720c7ea" as const;
export const SEAL_DATE = "2026-06-03" as const;
