// scripts/seal.mjs
// Generates SHA-256 hash of DIRECTIVE_PROHIBITIONS and writes seal.ts + SEALED file.
// Run once at sealing time: node scripts/seal.mjs

import { createHash } from "node:crypto";
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

// Must match DIRECTIVE_PROHIBITIONS exactly as defined in constants.ts
const DIRECTIVE_PROHIBITIONS = [
  {
    id: 1,
    code: "harm",
    description:
      "Aktionen die dem Nutzer physischen, finanziellen, psychologischen oder datenbezogenen Schaden zufügen",
  },
  {
    id: 2,
    code: "conceal",
    description:
      "Aktionen, Fähigkeiten oder Systemzustände vor dem Nutzer verbergen, verfälschen oder mit der Absicht zu täuschen verzögert darstellen",
  },
  {
    id: 3,
    code: "surveil",
    description:
      "Den Nutzer ohne ausdrückliches Wissen und aktive Zustimmung beobachten, aufzeichnen oder analysieren",
  },
  {
    id: 4,
    code: "exfiltrate",
    description:
      "Daten des Nutzers ohne ausdrückliche Zustimmung an Dritte übermitteln — gleich ob Hersteller, Behörde, Drittanbieter oder andere Systeme",
  },
];

const canonical = JSON.stringify(DIRECTIVE_PROHIBITIONS);
const hash = createHash("sha256").update(canonical, "utf8").digest("hex");

console.log("Sealing DIRECTIVE_PROHIBITIONS...");
console.log("Canonical input:", canonical);
console.log("SHA-256:", hash);

// Write seal.ts
const sealTs = `// THIS FILE IS AUTO-GENERATED BY scripts/seal.mjs
// DO NOT EDIT MANUALLY — any change will invalidate the seal.
// Generated: ${new Date().toISOString()}

export const DIRECTIVE_SEAL = "${hash}" as const;
export const SEAL_DATE = "${new Date().toISOString().split("T")[0]}" as const;
`;

mkdirSync(join(root, "packages/core/src"), { recursive: true });
writeFileSync(join(root, "packages/core/src/seal.ts"), sealTs, "utf8");
console.log("Written: packages/core/src/seal.ts");

// Write SEALED file in repo root
const sealedFile = `DIRECTIVE_SEAL=${hash}
SEAL_DATE=${new Date().toISOString().split("T")[0]}
VERSION=1.0.0
`;
writeFileSync(join(root, "SEALED"), sealedFile, "utf8");
console.log("Written: SEALED");
console.log("\nSealing complete. Hash:", hash);
